# BRUH

name: Build and release binaries
on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        description: 'Runner image name'
        default: 'windows-2022'

jobs:
  build-1:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: false
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-2:
    needs: build-1
    if: needs.build-1.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-3:
    needs: build-2
    if: needs.build-2.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-4:
    needs: build-3
    if: needs.build-3.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-5:
    needs: build-4
    if: needs.build-4.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-6:
    needs: build-5
    if: needs.build-5.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-7:
    needs: build-6
    if: needs.build-6.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-8:
    needs: build-7
    if: needs.build-7.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-9:
    needs: build-8
    if: needs.build-8.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-10:
    needs: build-9
    if: needs.build-9.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-11:
    needs: build-10
    if: needs.build-10.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-12:
    needs: build-11
    if: needs.build-11.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-13:
    needs: build-12
    if: needs.build-12.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-14:
    needs: build-13
    if: needs.build-13.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-15:
    needs: build-14
    if: needs.build-14.outputs.finished == 'false'
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-final:
    needs: build-15
    if: ${{ !cancelled() && !failure() }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\helium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          from_artifact: true
      - name: Build Helium installer
        id: stage2
        uses: ./.github/actions/stage
        with:
          gen_installer: true
          from_artifact: false
      - name: Generate user-facing artifacts
        id: stage3
        uses: ./.github/actions/stage
        with:
          do_package: true
          from_artifact: false
    outputs:
      finished: ${{ steps.stage3.outputs.finished }}
      version: ${{ steps.stage3.outputs.version }}

  publish-release:
    needs: [build-final]
    if: ${{ !cancelled() && !failure()
            && needs.build-final.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: helium-x86_64
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          fail_on_unmatched_files: true
          prerelease: true
          name: ${{ needs.build-final.outputs.version }}
          tag_name: ${{ needs.build-final.outputs.version }}
          文件: |
            helium*
    outputs:
      assets: ${{ steps.publish.outputs.assets }}
